// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitle': string;
  'result': string;
  'title': string;
  'titles': string;
}
export const cssExports: CssExports;
export default cssExports;
